### ISSUE TITLE
Non super user can export a super user object

### ISSUE THREAD

**Issue by StephenCote** [jrogelstad/featherbone#39]
A non-super user is able to export a super user object.  Because user object exports include credentials, this allows any user to authenticate to any other user in the system except for the initial administrative account (E.G.: postgres) as that password does appear to be stripped.

Issue:

1. Password should not be exported in plaintext (see related issue)
2. UI is greyed out for exporting user objects, however the action is still permitted
3. User is able to view and export an object that may not be desirable in a production system.

Expected result:

1. User is not able  to export object because the option is greyed out.
2. Optionally, user may not view other user object without authorization
3. Object export should not include plaintext password (see related issue)

**Comment by jrogelstad** [comment]
See issue #38 that I believe is already fixed. If that is the case there should be less danger here.

That said, by default all objects are granted full CRUD access to "everyone" (see authorization tab in feather definition). In production that authorization should be removed from design related feathers. I could make it less likely people would forget to revoke these privileges to an otherwise sensitive area by granting **no** privileges to design related feathers so that only super users can get to those objects and the design workbook itself unless authorization was consciously granted to other users or roles. What do you think?

**Comment by jrogelstad** [comment]
Went ahead and changed default installation so no authorization is granted to most design and admin objects, and read only on a couple that are needed for the client to function. Access to design and admin  workbooks are granted to no one either by default, so only a superuser sees and can edit these things by default.

It only changes the default setup on a new install, not an existing. A user could still grant authorization of everything to anyone and "everyone" if they wanted, though of course this would not be advised. Just making it easier here not to shoot yourself in the foot.
